"""Production content + demo-account seeding.

Deploying pushes code, not data — preview and production have separate MongoDB
databases. This module bundles the scenic-ride catalog, the store screenshots +
listing copy, and a ready-to-use demo login (with a little data) so they
auto-populate a fresh production database on startup.

Idempotent: every document is upserted by a natural key, so re-running on each
boot never duplicates and never clobbers unrelated (real-user) data.
"""
from __future__ import annotations

import gzip
import logging
from pathlib import Path

from bson import json_util

logger = logging.getLogger("seed_prod")

SEED_DIR = Path(__file__).resolve().parent / "seed_data"

# collection -> natural key used for the upsert
CONTENT_KEYS = {
    "scenic_routes": "id",
    "scenic_poi": "route_id",
    "screen_captures": "key",
    "app_meta": "key",
}
DEMO_KEYS = {
    "users": "email",
    "rider_profile": "id",
    "rider_prefs": "id",
    "ride_history": "id",
    "cycling_activities": "id",
    "calendar_weeks": "id",
}


def _load(path: Path) -> dict:
    if not path.exists():
        return {}
    raw = gzip.decompress(path.read_bytes()) if path.suffix == ".gz" else path.read_bytes()
    return json_util.loads(raw.decode("utf-8"))


async def _seed_bundle(db, bundle: dict, keys: dict[str, str]) -> int:
    written = 0
    for coll, docs in bundle.items():
        key = keys.get(coll)
        if not key or not docs:
            continue
        for doc in docs:
            if key not in doc:
                continue
            await db[coll].update_one({key: doc[key]}, {"$set": doc}, upsert=True)
            written += 1
    return written


def _iso_now() -> str:
    import datetime
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


# Extra curated POV scenic routes (idempotent, upserted by id on every boot so
# both preview and production stay in sync). Distances/climbs are approximate;
# per-km gradient profiles are generated by the scenic API from these.
EXTRA_SCENIC_ROUTES = [
    {
        "id": "dolomites-toblach-cortina", "name": "Dolomites: Toblach to Cortina",
        "place": "Toblach → Cortina d'Ampezzo", "country": "Italy", "region": "Dolomites",
        "youtube_id": "nKbiq_xsWDs", "duration_min": 60, "distance_km": 32.0, "elevation_m": 430,
        "tag": "Mountain · Epic", "terrain": "Alpine valley road with steady climbs",
        "difficulty": "Moderate", "surface": "Paved mountain road",
        "highlights": ["Toblach", "Lake Dobbiaco", "Cortina d'Ampezzo", "Dolomite peaks"],
        "description": "A stunning 4K POV ride through the Italian Dolomites from Toblach to Cortina d'Ampezzo, with dramatic alpine scenery and steady valley climbing.",
    },
    {
        "id": "dolomites-alpine-descent", "name": "Dolomites Alpine Descent",
        "place": "Rifugio Auronzo → Carbonin", "country": "Italy", "region": "Dolomites",
        "youtube_id": "U94MF1ZF81o", "duration_min": 30, "distance_km": 18.0, "elevation_m": 120,
        "tag": "Descent · Flowing", "terrain": "Long alpine descent with sweeping bends",
        "difficulty": "Easy", "surface": "Paved mountain road",
        "highlights": ["Rifugio Auronzo", "Tre Cime", "Schluderbach", "Carbonin"],
        "description": "A flowing 4K descent through the Dolomites — great for a relaxed spin with big mountain views.",
    },
    {
        "id": "bavarian-countryside", "name": "Bavarian Countryside",
        "place": "Bavaria", "country": "Germany", "region": "Bavaria",
        "youtube_id": "WPymzlvm9RE", "duration_min": 60, "distance_km": 24.0, "elevation_m": 180,
        "tag": "Countryside · Calm", "terrain": "Gentle countryside at the foot of the Alps",
        "difficulty": "Easy", "surface": "Paved country lanes",
        "highlights": ["Bavarian farmland", "Alpine foothills", "Villages"],
        "description": "A calm 60-minute ride through the charming Bavarian countryside — easy Zone 2 pacing.",
    },
    {
        "id": "holland-slow-ride", "name": "Holland Slow Ride",
        "place": "Dutch countryside", "country": "Netherlands", "region": "Holland",
        "youtube_id": "BcNlLJY53VY", "duration_min": 60, "distance_km": 22.0, "elevation_m": 40,
        "tag": "Flat · Relaxed", "terrain": "Flat Dutch countryside, no talking",
        "difficulty": "Easy", "surface": "Paved cycle paths",
        "highlights": ["Dutch polders", "Canals", "Windmills", "Quiet lanes"],
        "description": "A slow-TV, no-talking POV journey through the flat Dutch countryside — perfect for steady endurance.",
    },
    {
        "id": "norway-trondheim", "name": "Norway: Trondheim",
        "place": "Trondheim", "country": "Norway", "region": "Trøndelag",
        "youtube_id": "6evwVmbSi4c", "duration_min": 60, "distance_km": 25.0, "elevation_m": 300,
        "tag": "Nordic · Scenic", "terrain": "Coastal Nordic roads with gentle climbs",
        "difficulty": "Moderate", "surface": "Paved roads",
        "highlights": ["Trondheim", "Fjord views", "Nordic scenery"],
        "description": "A 4K hour-long virtual ride through Trondheim, Norway — crisp Nordic scenery and fjord views.",
    },
]


async def _seed_extra_scenic(db) -> int:
    """Upsert curated POV scenic routes by id (published), preserving created_at."""
    written = 0
    for i, r in enumerate(EXTRA_SCENIC_ROUTES):
        doc = dict(r)
        doc.setdefault("status", "published")
        doc.setdefault("thumbnail_url", None)
        doc["sort"] = 100 + i
        doc["updated_at"] = _iso_now()
        await db.scenic_routes.update_one(
            {"id": doc["id"]},
            {"$set": doc, "$setOnInsert": {"created_at": _iso_now()}},
            upsert=True,
        )
        written += 1
    return written


async def seed_production_data(db) -> None:
    """Seed bundled content + demo account. Safe to run on every startup."""
    try:
        content = _load(SEED_DIR / "content_seed.json.gz")
        if not content:
            content = _load(SEED_DIR / "content_seed.json")
        demo = _load(SEED_DIR / "demo_seed.json")

        n1 = await _seed_bundle(db, content, CONTENT_KEYS)
        n2 = await _seed_bundle(db, demo, DEMO_KEYS)
        n3 = await _seed_extra_scenic(db)
        logger.info("Production seed complete — content docs: %s, demo docs: %s, extra scenic: %s", n1, n2, n3)
    except Exception:
        logger.exception("production seeding failed")
