// "Ride Beyond" — Roujaune's default ADVANCED 12-week performance plan. Three
// primary rides/week for experienced cyclists. Phase 1 (Weeks 1–4) is authored
// here; Phases 2–3 append when provided. Same shape as the other programs so the
// shared plan engine + Live Workout catalog drive it.
import type { Interval, Session, Week, Phase, Program } from "./couch-to-road";

const iv = (
  name: string,
  minutes: number,
  rpe: string,
  cadence?: string,
  extra?: Partial<Interval>,
): Interval => ({ name, minutes, rpe, ...(cadence ? { cadence } : {}), ...extra });

const restDay = (): Session => ({
  day: "Monday", type: "rest", title: "Complete Rest or Gentle Mobility",
  notes: "No scheduled riding. Optional gentle mobility, hydration, food and sleep.",
});
const recoveryDay = (title: string, duration: string): Session => ({
  day: "Friday", type: "recovery", title, duration, optional: true,
});

// ---------------------------------------------------------------- WEEK 1
const week1: Week = {
  number: 1,
  title: "Establish the Baseline",
  objective:
    "Establish current advanced fitness benchmarks and settle into the rhythm of the program. Finish challenged, not depleted.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Advanced Performance Baseline", rideLabel: "Ride 1",
      duration: "75–90 min", category: "Baseline Assessment and Pacing Control", environment: "Indoor or outdoor",
      goal: "Establish your current aerobic, sustained-power and high-intensity baseline.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3", "80–90 rpm"),
        iv("Build", 5, "RPE 3–4"),
        iv("Cadence Spins", 4, "RPE 4", "105–115 rpm"),
        iv("Prep", 3, "RPE 4–5"),
        iv("Aerobic Benchmark", 15, "RPE 4–5", "80–95 rpm"),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Sustained Benchmark", 12, "RPE 7", "82–94 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("VO2 Control 1", 2, "RPE 8"),
        iv("Recovery", 3, "RPE 2"),
        iv("VO2 Control 2", 2, "RPE 8"),
        iv("Recovery", 3, "RPE 2"),
        iv("VO2 Control 3", 2, "RPE 8"),
        iv("Cool-Down", 12, "RPE 1–2", "60–75 rpm"),
      ],
      easierOption: "Complete two VO2 control efforts, or reduce the sustained benchmark to 10 minutes.",
      completionMessage:
        "Your baseline is not an exam — it is the starting point from which your training becomes personal.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Cadence Range and Aerobic Control", rideLabel: "Ride 2",
      duration: "70–80 min", category: "Pedalling Efficiency", environment: "Indoor or outdoor",
      goal: "Maintain smooth power while changing cadence — stay efficient across pedalling speeds.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Cadence Spins", 4, "RPE 4", "100–110 rpm"),
        iv("Round 1 · Steady", 6, "RPE 4", "80–85 rpm"),
        iv("Round 1 · Lift", 5, "RPE 5", "90–95 rpm"),
        iv("Round 1 · High", 3, "RPE 5–6", "100–105 rpm"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Round 2 · Steady", 6, "RPE 4", "80–85 rpm"),
        iv("Round 2 · Lift", 5, "RPE 5", "90–95 rpm"),
        iv("Round 2 · High", 3, "RPE 5–6", "100–105 rpm"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Tempo 1", 6, "RPE 6", "85–95 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Tempo 2", 6, "RPE 6", "85–95 rpm"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete two cadence rounds and one closing tempo interval.",
      completionMessage: "Your cadence may change, but your control should not.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Advanced Foundation Endurance Ride", rideLabel: "Ride 3",
      duration: "120–150 min", category: "Aerobic Durability", environment: "Indoor or outdoor",
      goal: "Build the aerobic endurance required for advanced training; finish as strong as you started.",
      intervals: [
        iv("Opening Endurance", 30, "RPE 3", "80–92 rpm"),
        iv("Endurance Block 1", 15, "RPE 5", "80–95 rpm"),
        iv("Recovery", 8, "RPE 3"),
        iv("Endurance Block 2", 15, "RPE 5", "80–95 rpm"),
        iv("Recovery", 8, "RPE 3"),
        iv("Endurance Block 3", 15, "RPE 5", "80–95 rpm"),
        iv("Final Endurance", 24, "RPE 4–5"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Shorten or omit the final endurance section if form, comfort or fuelling decline.",
      completionMessage:
        "Endurance is measured not by how hard you begin, but by how well you are still riding near the end.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
  reflection: ["Was the 12-minute benchmark paced evenly?", "Did you finish tired but composed?"],
};

// ---------------------------------------------------------------- WEEK 2
const week2: Week = {
  number: 2,
  title: "Tempo Capacity",
  objective: "Increase sustained aerobic pressure and introduce longer tempo work — smooth, purposeful, repeatable.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Sustained Tempo Development", rideLabel: "Ride 4",
      duration: "80–90 min", category: "Sustainable Speed", environment: "Indoor or outdoor",
      goal: "Sustain a strong pace below threshold — demanding enough to adapt, controlled enough to repeat.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Cadence Spins", 3, "RPE 4", "100–110 rpm"),
        iv("Prep", 3, "RPE 5"),
        iv("Tempo 1", 12, "RPE 6", "82–95 rpm"),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Tempo 2", 12, "RPE 6", "82–95 rpm"),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Tempo 3", 12, "RPE 6", "82–95 rpm"),
        iv("Leg-Speed 1", 1, "RPE 6", "110–120 rpm"),
        iv("Leg-Speed 2", 1, "RPE 6", "110–120 rpm"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two tempo intervals; keep leg-speed efforts controlled, not maximal.",
      completionMessage: "Tempo should feel strong enough to matter and controlled enough to repeat.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Aerobic Endurance with Cadence Changes", rideLabel: "Ride 5",
      duration: "75–90 min", category: "Aerobic Stability under Cadence Variation", environment: "Indoor or outdoor",
      goal: "Stay aerobically stable while cadence and resistance change — efficiency for rolling roads and wind.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Cadence Spins", 3, "RPE 4", "100–110 rpm"),
        iv("Round 1 · Mid", 6, "RPE 4–5", "85–90 rpm"),
        iv("Round 1 · High", 4, "RPE 4–5", "95–100 rpm"),
        iv("Round 1 · Low", 3, "RPE 4–5", "75–80 rpm"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Round 2 · Mid", 6, "RPE 4–5", "85–90 rpm"),
        iv("Round 2 · High", 4, "RPE 4–5", "95–100 rpm"),
        iv("Round 2 · Low", 3, "RPE 4–5", "75–80 rpm"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Round 3 · Mid", 6, "RPE 4–5", "85–90 rpm"),
        iv("Round 3 · High", 4, "RPE 4–5", "95–100 rpm"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete three rounds instead of four; avoid grinding at low cadence.",
      completionMessage: "The gear may change. The terrain may change. Your rhythm stays yours.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Progressive Endurance Ride", rideLabel: "Ride 6",
      duration: "150–165 min", category: "Progressive Pacing and Endurance Control", environment: "Indoor or outdoor",
      goal: "Build intensity gradually across a long ride — finish stronger than you began, without losing control.",
      intervals: [
        iv("Block 1 · Easy", 45, "RPE 3"),
        iv("Block 2 · Steady", 45, "RPE 4"),
        iv("Block 3 · Strong", 30, "RPE 5"),
        iv("Block 4 · Tempo", 15, "RPE 5–6"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "End after Block 3 if readiness is reduced; keep the final block controlled, never all-out.",
      completionMessage: "A progressive ride becomes stronger, not sloppier.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 3
const week3: Week = {
  number: 3,
  title: "Threshold Introduction",
  objective: "The most demanding week of Phase 1: threshold control, seated climbing strength and repeated sustained efforts.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Controlled Threshold Development", rideLabel: "Ride 7",
      duration: "85–95 min", category: "Sustained Threshold Power", environment: "Indoor or outdoor",
      goal: "Sustain a demanding effort near threshold — every interval consistent, never over-cooked on the first.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Openers", 3, "RPE 6"),
        iv("Prep", 4, "RPE 3–4"),
        iv("Threshold 1", 8, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Threshold 2", 8, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Threshold 3", 8, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Threshold 4", 8, "RPE 7–8", "82–94 rpm"),
        iv("Aerobic Finish", 8, "RPE 5"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete three threshold intervals, or hold them at RPE 7.",
      completionMessage: "Threshold is not chaos — it is controlled discomfort held with purpose.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Seated Climbing Strength and Control", rideLabel: "Ride 8",
      duration: "75–90 min", category: "Muscular Endurance and Climbing Torque", environment: "Indoor or outdoor",
      goal: "Develop the force for sustained climbing while reinforcing controlled pedalling technique.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Torque Openers", 3, "RPE 5", "75–80 rpm"),
        iv("Prep", 3, "RPE 3"),
        iv("Seated Climb 1", 6, "RPE 6–7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Seated Climb 2", 6, "RPE 6–7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Seated Climb 3", 6, "RPE 6–7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Seated Climb 4", 6, "RPE 6–7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Seated Climb 5", 6, "RPE 6–7", "60–70 rpm", { position: "Seated" }),
        iv("Cadence Finish", 5, "RPE 6", "90–100 rpm"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete three or four seated climbs; keep cadence controllable and stop if knee discomfort develops.",
      completionMessage: "Climbing strength comes from controlled pressure, not from fighting the bicycle.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Hills and Endurance", rideLabel: "Ride 9",
      duration: "150–180 min", category: "Climbing Durability", environment: "Indoor or outdoor",
      goal: "Combine aerobic endurance with sustained climbing — controlled power while managing a long ride.",
      intervals: [
        iv("Opening Endurance", 25, "RPE 3–4"),
        iv("Climb 1", 9, "RPE 6", "65–80 rpm"),
        iv("Endurance", 12, "RPE 3–4"),
        iv("Climb 2", 9, "RPE 6", "65–80 rpm"),
        iv("Endurance", 12, "RPE 3–4"),
        iv("Climb 3", 9, "RPE 6", "65–80 rpm"),
        iv("Endurance", 12, "RPE 3–4"),
        iv("Climb 4", 9, "RPE 6", "65–80 rpm"),
        iv("Controlled Endurance Finish", 20, "RPE 3–4"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete three climbs; keep the remaining ride at RPE 3–4.",
      completionMessage: "A strong climber does not conquer the first minute — a strong climber controls the whole ascent.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 4
const week4: Week = {
  number: 4,
  title: "Consolidate and Reassess",
  weekType: "Reduced-volume consolidation and readiness assessment",
  objective: "Reduce volume while retaining purposeful intensity. Absorb the first three weeks and confirm readiness for Phase 2.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Tempo and Threshold Consolidation", rideLabel: "Ride 10",
      duration: "70–80 min", category: "Maintaining Intensity with Reduced Volume", environment: "Indoor or outdoor",
      goal: "Hold intensity with less total work — sharp, clean, energy remaining at the end.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 4, "RPE 4"),
        iv("Cadence Spins", 2, "RPE 4", "100–110 rpm"),
        iv("Tempo 1", 10, "RPE 6", "82–95 rpm"),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Tempo 2", 10, "RPE 6", "82–95 rpm"),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Threshold 1", 6, "RPE 7", "82–94 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Threshold 2", 6, "RPE 7", "82–94 rpm"),
        iv("Sharp 1", 0.5, "RPE 8"),
        iv("Sharp 2", 0.5, "RPE 8"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete one threshold interval and two short RPE 8 efforts.",
      completionMessage: "Reduced volume does not mean reduced purpose.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~25 min" },
    {
      day: "Thursday", type: "cycling", title: "Aerobic Maintenance and Technique", rideLabel: "Ride 11",
      duration: "60–75 min", category: "Recovery, Aerobic Maintenance and Cadence", environment: "Indoor or outdoor",
      goal: "Easy aerobic maintenance with light, smooth high-cadence work — finish better than you started.",
      intervals: [
        iv("Easy Start", 10, "RPE 2–3"),
        iv("Aerobic", 8, "RPE 3–4"),
        iv("Spin 1", 1, "RPE 4", "105–115 rpm"),
        iv("Recovery", 2, "RPE 2"),
        iv("Spin 2", 1, "RPE 4", "105–115 rpm"),
        iv("Recovery", 2, "RPE 2"),
        iv("Spin 3", 1, "RPE 4", "105–115 rpm"),
        iv("Recovery", 2, "RPE 2"),
        iv("Spin 4", 1, "RPE 4", "105–115 rpm"),
        iv("Aerobic", 8, "RPE 3"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete four high-cadence spins total; keep everything easy.",
      completionMessage: "Fast legs do not need frantic movement. Stay light, smooth and composed.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Phase 1 Confidence Endurance Ride", rideLabel: "Ride 12",
      duration: "120–150 min", category: "Phase Consolidation and Readiness", environment: "Indoor or outdoor",
      goal: "Bring together endurance, tempo, threshold, cadence and fuelling — confirm your strength is repeatable.",
      intervals: [
        iv("Opening Endurance", 30, "RPE 3–4"),
        iv("Tempo 1", 15, "RPE 5–6", "82–95 rpm"),
        iv("Recovery", 8, "RPE 3"),
        iv("Tempo 2", 15, "RPE 5–6", "82–95 rpm"),
        iv("Recovery", 6, "RPE 3"),
        iv("Threshold", 8, "RPE 7", "82–94 rpm"),
        iv("Steady Aerobic Finish", 20, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Reduce the tempo blocks to 10 minutes and hold the threshold effort at RPE 6.",
      completionMessage: "Phase 1 is complete when your strength feels repeatable — not accidental.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
  reflection: [
    "Did the tempo efforts feel controlled and the threshold effort evenly paced?",
    "Did cadence remain stable and fuelling effective?",
    "Did you recover normally, with no persistent pain or excessive fatigue?",
    "Are you ready for Phase 2 — Power and Durability?",
  ],
};

const phase1: Phase = {
  number: 1,
  name: "Performance Foundation",
  weeksLabel: "Weeks 1–4",
  objective:
    "Establish the rider's advanced performance baseline and develop the control, aerobic durability and technical efficiency needed for the rest of the program.",
  focus: [
    "Performance assessment and aerobic efficiency.",
    "Tempo control and a threshold introduction.",
    "Cadence development and seated climbing strength.",
    "Progressive endurance toward 2.5–3 hours.",
    "Proactive fuelling and hydration; technique under fatigue.",
    "A reduced-volume Week 4 and a Phase 2 readiness assessment.",
  ],
  cadenceQuote: "Cadence should never be forced at the expense of comfort, coordination or safe technique.",
  weeks: [week1, week2, week3, week4],
  complete: {
    heading: "PHASE 1 COMPLETE — PERFORMANCE FOUNDATION",
    summary: [
      "Four weeks completed; twelve advanced cycling workouts available.",
      "Performance benchmarks established; aerobic efficiency and tempo control developed.",
      "Threshold intervals and seated climbing strength introduced.",
      "Progressive endurance to 2.5–3 hours; proactive fuelling practised.",
      "Reduced-volume consolidation week and Phase 2 readiness assessment completed.",
    ],
    coachMessage:
      "You have built more than fitness — you have established the control, consistency and durability required for advanced performance training. The next phase will ask you to produce more power, climb with greater strength and complete quality work after fatigue accumulates. Ride Beyond — stronger for longer, ready when the road demands more.",
  },
};

// ---------------------------------------------------------------- WEEK 5
const week5: Week = {
  number: 5,
  title: "Sustainable Power",
  objective:
    "Begin producing more sustained power — longer tempo intervals, cadence control under load and durable long-ride endurance.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Advanced Tempo Strength Builder", rideLabel: "Ride 13",
      duration: "90–100 min", category: "Sustainable Tempo Power and Muscular Endurance", environment: "Indoor or outdoor",
      goal: "Build the strength to create sustained pressure — and the control to hold it.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Surge 1", 1, "RPE 5–6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Surge 2", 1, "RPE 5–6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Surge 3", 1, "RPE 5–6"),
        iv("Settle", 4, "RPE 3"),
        iv("Tempo 1 · Strength", 10, "RPE 6–7", "75–85 rpm"),
        iv("Tempo 1 · Lift", 5, "RPE 6–7", "85–95 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("Tempo 2 · Strength", 10, "RPE 6–7", "75–85 rpm"),
        iv("Tempo 2 · Lift", 5, "RPE 6–7", "85–95 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("Tempo 3 · Strength", 10, "RPE 6–7", "75–85 rpm"),
        iv("Tempo 3 · Lift", 5, "RPE 6–7", "85–95 rpm"),
        iv("Tempo Finish", 5, "RPE 5", "95–100 rpm"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two tempo intervals; keep the finish light and controlled.",
      completionMessage: "Strength is not only how much pressure you can create. It is how long you can control it.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Cadence Under Load", rideLabel: "Ride 14",
      duration: "75–90 min", category: "Maintaining Power through Cadence and Resistance Changes", environment: "Indoor or outdoor",
      goal: "Hold the same calm control as cadence and resistance change beneath you.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Spin-Up 1", 0.5, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 2", 0.5, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 3", 0.5, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Torque 1", 1, "RPE 5", "75–80 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Torque 2", 1, "RPE 5", "75–80 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Round 1 · Low", 4, "RPE 6", "65–72 rpm"),
        iv("Round 1 · Mid", 4, "RPE 6", "85–92 rpm"),
        iv("Round 1 · High", 2, "RPE 6", "100–108 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Round 2 · Low", 4, "RPE 6", "65–72 rpm"),
        iv("Round 2 · Mid", 4, "RPE 6", "85–92 rpm"),
        iv("Round 2 · High", 2, "RPE 6", "100–108 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Round 3 · Low", 4, "RPE 6", "65–72 rpm"),
        iv("Round 3 · Mid", 4, "RPE 6", "85–92 rpm"),
        iv("Round 3 · High", 2, "RPE 6", "100–108 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Round 4 · Low", 4, "RPE 6", "65–72 rpm"),
        iv("Round 4 · Mid", 4, "RPE 6", "85–92 rpm"),
        iv("Round 4 · High", 2, "RPE 6", "100–108 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete three rounds; avoid grinding at the lowest cadence.",
      completionMessage: "Different cadence. Different resistance. The same calm control.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Long Steady Endurance Ride", rideLabel: "Ride 15",
      duration: "165–195 min", category: "Aerobic Durability and Sustained Endurance", environment: "Indoor or outdoor",
      goal: "Build aerobic durability one controlled hour at a time; practise your goal-ride fuelling.",
      intervals: [
        iv("Opening Endurance", 45, "RPE 3", "80–92 rpm"),
        iv("Endurance Block 1", 20, "RPE 5", "80–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Endurance Block 2", 20, "RPE 5", "80–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Endurance Block 3", 20, "RPE 5", "80–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Final Endurance", 30, "RPE 4–5"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "End after the third block, or shorten the final endurance section if fuelling or form declines.",
      notes: "Fuelling focus: begin eating and drinking early and fuel consistently — practise the strategy intended for your goal rides.",
      completionMessage: "A long ride is built one controlled hour at a time.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 6
const week6: Week = {
  number: 6,
  title: "Climbing Power",
  objective: "Develop seated and standing climbing power, positional control and climbing durability across a long ride.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Seated Climbing Strength", rideLabel: "Ride 16",
      duration: "85–95 min", category: "Climbing Torque and Muscular Endurance", environment: "Indoor or outdoor",
      goal: "Build climbing power that begins with control and finishes with confidence.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Build", 4, "RPE 4"),
        iv("Torque Opener 1", 1, "RPE 5–6", "70–75 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Torque Opener 2", 1, "RPE 5–6", "70–75 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Torque Opener 3", 1, "RPE 5–6", "70–75 rpm"),
        iv("Settle", 3, "RPE 3"),
        iv("Seated Climb 1", 8, "RPE 7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Seated Climb 2", 8, "RPE 7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Seated Climb 3", 8, "RPE 7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Seated Climb 4", 8, "RPE 7", "60–70 rpm", { position: "Seated" }),
        iv("Recovery", 5, "RPE 2–3"),
        iv("Standing Surge 1", 0.75, "RPE 7–8", undefined, { position: "Standing" }),
        iv("Recovery", 2, "RPE 2–3"),
        iv("Standing Surge 2", 0.75, "RPE 7–8", undefined, { position: "Standing" }),
        iv("Recovery", 2, "RPE 2–3"),
        iv("Standing Surge 3", 0.75, "RPE 7–8", undefined, { position: "Standing" }),
        iv("Recovery", 2, "RPE 2–3"),
        iv("Standing Surge 4", 0.75, "RPE 7–8", undefined, { position: "Standing" }),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete three seated climbs and two standing surges; keep the standing efforts controlled, not maximal.",
      completionMessage: "Climbing power begins with control and finishes with confidence.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Aerobic Endurance with Hill Skills", rideLabel: "Ride 17",
      duration: "80–95 min", category: "Climbing Technique and Positional Control", environment: "Indoor or outdoor",
      goal: "Stand with purpose, sit with control, and keep the climb flowing through every transition.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Opener 1", 1, "RPE 5"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 5"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 5"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Standing Prep 1", 0.33, "RPE 5–6", undefined, { position: "Standing" }),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Standing Prep 2", 0.33, "RPE 5–6", undefined, { position: "Standing" }),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Climb 1", 3, "RPE 6"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Climb 2", 3, "RPE 6"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Climb 3", 3, "RPE 6"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Climb 4", 3, "RPE 6"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Climb 5", 3, "RPE 6"),
        iv("Recovery", 3, "RPE 2–3"),
        iv("Climb 6", 3, "RPE 6"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete four climbing efforts; keep every transition smooth and avoid sudden surges.",
      notes: "During each effort, alternate seated and standing every 30–60 seconds and keep the effort smooth through each transition.",
      completionMessage: "Stand with purpose. Sit with control. Keep the climb flowing.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Hills and Endurance", rideLabel: "Ride 18",
      duration: "180–210 min", category: "Climbing Durability and Long-Ride Fuelling", environment: "Indoor or outdoor",
      goal: "Respect every ascent, recover for the next, and build durable climbing endurance.",
      intervals: [
        iv("Opening Endurance", 30, "RPE 3–4"),
        iv("Climb 1", 9, "RPE 5–6", "65–80 rpm"),
        iv("Endurance", 14, "RPE 3–4"),
        iv("Climb 2", 9, "RPE 5–6", "65–80 rpm"),
        iv("Endurance", 14, "RPE 3–4"),
        iv("Climb 3", 9, "RPE 5–6", "65–80 rpm"),
        iv("Endurance", 14, "RPE 3–4"),
        iv("Climb 4", 9, "RPE 5–6", "65–80 rpm"),
        iv("Endurance", 14, "RPE 3–4"),
        iv("Climb 5", 9, "RPE 5–6", "65–80 rpm"),
        iv("Endurance", 14, "RPE 3–4"),
        iv("Climb 6 · Strong", 9, "RPE 7", "65–80 rpm"),
        iv("Controlled Endurance Finish", 18, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete five climbs and keep the final climb at RPE 5–6; ride flats and descents controlled.",
      notes: "Pace early climbs conservatively, select gearing for the gradient, stand only when useful, and fuel from the first hour.",
      completionMessage: "Climbing durability is built by respecting every ascent — and recovering for the next one.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 7
const week7: Week = {
  number: 7,
  title: "Threshold and VO₂ Development",
  objective: "The most demanding week of Phase 2: longer threshold work, controlled VO₂ intervals and quality effort late in a long ride.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Threshold Progression", rideLabel: "Ride 19",
      duration: "90–105 min", category: "Sustained Threshold Power and Repeatability", environment: "Indoor or outdoor",
      goal: "Threshold power matters most when you can repeat it — hold each effort evenly.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Opener 1", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Sharpener 1", 0.5, "RPE 7"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Sharpener 2", 0.5, "RPE 7"),
        iv("Settle", 2, "RPE 2–3"),
        iv("Threshold 1", 12, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("Threshold 2", 12, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("Threshold 3", 12, "RPE 7–8", "82–94 rpm"),
        iv("Recovery", 6, "RPE 2–3"),
        iv("VO2 Finish 1", 1, "RPE 8"),
        iv("Recovery", 2, "RPE 2–3"),
        iv("VO2 Finish 2", 1, "RPE 8"),
        iv("Recovery", 2, "RPE 2–3"),
        iv("VO2 Finish 3", 1, "RPE 8"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two threshold intervals at RPE 7 and two one-minute finishing efforts.",
      completionMessage: "Threshold power matters most when you can repeat it.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "VO₂ Power Intervals", rideLabel: "Ride 20",
      duration: "75–90 min", category: "Controlled High-Intensity Aerobic Power", environment: "Indoor or outdoor",
      goal: "Keep the final interval looking like cycling — quality across the whole set, not survival.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Build", 4, "RPE 4"),
        iv("Opener 1", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 6"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 1", 0.5, "RPE 7–8"),
        iv("Recovery", 1.5, "RPE 2–3"),
        iv("Primer 2", 0.5, "RPE 7–8"),
        iv("Settle", 2, "RPE 2–3"),
        iv("VO2 Interval 1", 3, "RPE 8–9", "90–105 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("VO2 Interval 2", 3, "RPE 8–9", "90–105 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("VO2 Interval 3", 3, "RPE 8–9", "90–105 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("VO2 Interval 4", 3, "RPE 8–9", "90–105 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("VO2 Interval 5", 3, "RPE 8–9", "90–105 rpm"),
        iv("Cool-Down", 14, "RPE 1–2"),
      ],
      easierOption: "Complete three or four VO₂ intervals; stop the set if power, cadence or technique declines substantially.",
      completionMessage: "High intensity works when the final interval still looks like cycling — not survival.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Goal-Specific Durability Ride", rideLabel: "Ride 21",
      duration: "180–225 min", category: "Producing Quality Effort after Fatigue", environment: "Indoor or outdoor",
      goal: "Late-ride strength is prepared long before the final interval begins.",
      intervals: [
        iv("Controlled Opening", 60, "RPE 3–4"),
        iv("Steady Endurance", 25, "RPE 3–4"),
        iv("Effort 1", 15, "RPE 6", "82–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Effort 2", 15, "RPE 6", "82–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Effort 3", 15, "RPE 6", "82–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Final Performance Effort", 10, "RPE 6–7"),
        iv("Endurance Finish", 15, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "When readiness is reduced, replace the final effort with 10–20 minutes at RPE 4–5.",
      notes: "Goal-specific: climbers ride the efforts on sustained climbs; endurance riders use steady terrain; event/speed riders use rolling terrain with smooth pace changes. Fuel consistently and avoid early surges.",
      completionMessage: "Late-ride strength is prepared long before the final interval begins.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 8
const week8: Week = {
  number: 8,
  title: "Consolidate and Absorb",
  weekType: "Reduced-volume consolidation and performance readiness",
  objective: "Maintain hard-earned tempo, threshold and climbing fitness with less total work, and confirm readiness for Phase 3.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Short Tempo Consolidation", rideLabel: "Ride 22",
      duration: "65–75 min", category: "Tempo Maintenance and Short High-Intensity Activation", environment: "Indoor or outdoor",
      goal: "Keep the engine awake without draining the tank.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 4, "RPE 4"),
        iv("Spin-Up 1", 0.33, "RPE 4", "100–110 rpm"),
        iv("Recovery", 0.66, "RPE 2–3"),
        iv("Spin-Up 2", 0.33, "RPE 4", "100–110 rpm"),
        iv("Recovery", 0.66, "RPE 2–3"),
        iv("Spin-Up 3", 0.33, "RPE 4", "100–110 rpm"),
        iv("Tempo 1", 8, "RPE 6", "82–95 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Tempo 2", 8, "RPE 6", "82–95 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Tempo 3", 8, "RPE 6", "82–95 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Sharp 1", 0.5, "RPE 8"),
        iv("Recovery", 1.5, "RPE 2–3"),
        iv("Sharp 2", 0.5, "RPE 8"),
        iv("Recovery", 1.5, "RPE 2–3"),
        iv("Sharp 3", 0.5, "RPE 8"),
        iv("Recovery", 1.5, "RPE 2–3"),
        iv("Sharp 4", 0.5, "RPE 8"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two tempo intervals and two short RPE 8 efforts.",
      completionMessage: "Keep the engine awake without draining the tank.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~25 min" },
    {
      day: "Thursday", type: "cycling", title: "Strength and Cadence Consolidation", rideLabel: "Ride 23",
      duration: "65–80 min", category: "Maintaining Climbing Strength and Cadence Range", environment: "Indoor or outdoor",
      goal: "Turn hard-earned fitness into dependable performance.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Spin-Up 1", 0.33, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 2", 0.33, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 3", 0.33, "RPE 4", "100–110 rpm"),
        iv("Recovery", 1, "RPE 2–3"),
        iv("Build", 2, "RPE 4"),
        iv("Round 1 · Strength", 5, "RPE 6", "65–72 rpm"),
        iv("Round 1 · Smooth", 5, "RPE 5", "90–95 rpm"),
        iv("Round 1 · Fast", 2, "RPE 5", "105–110 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Round 2 · Strength", 5, "RPE 6", "65–72 rpm"),
        iv("Round 2 · Smooth", 5, "RPE 5", "90–95 rpm"),
        iv("Round 2 · Fast", 2, "RPE 5", "105–110 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Round 3 · Strength", 5, "RPE 6", "65–72 rpm"),
        iv("Round 3 · Smooth", 5, "RPE 5", "90–95 rpm"),
        iv("Round 3 · Fast", 2, "RPE 5", "105–110 rpm"),
        iv("Recovery", 4, "RPE 2–3"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete two rounds; keep the low-cadence strength blocks comfortable.",
      completionMessage: "Consolidation turns hard-earned fitness into dependable performance.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Phase 2 Confidence Endurance Ride", rideLabel: "Ride 24",
      duration: "150–180 min", category: "Phase Consolidation and Performance Readiness", environment: "Indoor or outdoor",
      goal: "Confirm you can still produce quality after the easy kilometres are gone.",
      intervals: [
        iv("Opening Endurance", 40, "RPE 3–4"),
        iv("Steady Endurance", 20, "RPE 3–4"),
        iv("Tempo 1", 20, "RPE 6", "82–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Tempo 2", 20, "RPE 6", "82–95 rpm"),
        iv("Recovery", 10, "RPE 3"),
        iv("Threshold", 10, "RPE 7", "82–94 rpm"),
        iv("Recovery", 5, "RPE 3"),
        iv("VO2 1", 1, "RPE 8"),
        iv("Recovery", 2, "RPE 2–3"),
        iv("VO2 2", 1, "RPE 8"),
        iv("Recovery", 2, "RPE 2–3"),
        iv("VO2 3", 1, "RPE 8"),
        iv("Recovery", 2, "RPE 2–3"),
        iv("VO2 4", 1, "RPE 8"),
        iv("Endurance Finish", 12, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Reduce the tempo blocks to 15 minutes and hold the threshold effort at RPE 6.",
      notes: "Complete the threshold and one-minute efforts during the second half; leave time to finish with controlled endurance.",
      completionMessage: "Phase 2 is complete when you can still produce quality after the easy kilometres are gone.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
  reflection: [
    "Could you complete 30–40 minutes of quality threshold work across the week?",
    "Did your VO₂ efforts stay controlled and repeatable?",
    "Did climbing power hold without excessive cadence loss, seated and standing?",
    "Could you still produce tempo or threshold effort late in the long rides?",
    "Are you ready for Phase 3 — goal-specific performance training?",
  ],
};

const phase2: Phase = {
  number: 2,
  name: "Power and Durability",
  weeksLabel: "Weeks 5–8",
  objective:
    "Build on the aerobic foundation to produce more sustained power — longer threshold efforts, controlled VO₂ work, stronger climbing and quality effort produced after fatigue has accumulated.",
  focus: [
    "Longer, sustainable tempo and threshold intervals.",
    "Seated and standing climbing power and muscular endurance.",
    "Controlled VO₂ intervals and faster recovery between hard efforts.",
    "Cadence control under changing resistance.",
    "Useful power late in three-to-four-hour rides.",
    "Long-ride fuelling and hydration under fatigue.",
  ],
  milestone: [
    "Complete 30–40 minutes of quality threshold work.",
    "Sustain longer tempo intervals and repeat controlled VO₂ efforts.",
    "Maintain climbing power without excessive cadence loss.",
    "Transition smoothly between seated and standing climbing.",
    "Recover predictably between demanding intervals.",
    "Produce tempo or threshold effort late in a long ride.",
    "Complete longer rides with consistent fuelling and technique under fatigue.",
  ],
  cadenceQuote: "Different cadence. Different resistance. The same calm control.",
  weeks: [week5, week6, week7, week8],
  complete: {
    heading: "PHASE 2 COMPLETE — POWER AND DURABILITY",
    summary: [
      "Eight total weeks completed; twenty-four advanced cycling workouts available.",
      "Sustained tempo and 30–40 minutes of quality threshold work developed.",
      "Controlled VO₂ intervals and stronger seated and standing climbing established.",
      "Quality effort produced late in three-to-four-hour rides.",
      "Long-ride fuelling and hydration practised under accumulated fatigue.",
      "Reduced-volume consolidation week and Phase 3 readiness confirmed.",
    ],
    coachMessage:
      "You are now producing real power and holding it under fatigue — the hallmark of an advanced rider. You climb with more strength, recover faster between hard efforts and still ride well when the easy kilometres are gone. Phase 3 turns this engine into goal-specific performance and prepares you for your Achievement Ride. Ride Beyond — the strongest work is still ahead, and you are ready for it.",
  },
};

// ---------------------------------------------------------------- WEEK 9
const week9: Week = {
  number: 9,
  title: "Changes of Pace",
  objective: "Move repeatedly between threshold and above-threshold effort, develop leg speed and complete a goal-simulation ride.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Goal-Specific Over-Under Intervals", rideLabel: "Ride 25",
      duration: "90–100 min", category: "Threshold Control and Changes of Pace", environment: "Indoor or outdoor",
      goal: "Control the surge, settle back into strength and keep moving forward.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Opener 1", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 1", 0.5, "RPE 7–8"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 2", 0.5, "RPE 7–8"),
        iv("Settle", 2, "RPE 2–3"),
        iv("B1 · Under 1", 2, "RPE 7", "82–94 rpm"), iv("B1 · Over 1", 1, "RPE 8"),
        iv("B1 · Under 2", 2, "RPE 7", "82–94 rpm"), iv("B1 · Over 2", 1, "RPE 8"),
        iv("B1 · Under 3", 2, "RPE 7", "82–94 rpm"), iv("B1 · Over 3", 1, "RPE 8"),
        iv("B1 · Under 4", 2, "RPE 7", "82–94 rpm"), iv("B1 · Over 4", 1, "RPE 8"),
        iv("Recovery", 7, "RPE 2–3"),
        iv("B2 · Under 1", 2, "RPE 7", "82–94 rpm"), iv("B2 · Over 1", 1, "RPE 8"),
        iv("B2 · Under 2", 2, "RPE 7", "82–94 rpm"), iv("B2 · Over 2", 1, "RPE 8"),
        iv("B2 · Under 3", 2, "RPE 7", "82–94 rpm"), iv("B2 · Over 3", 1, "RPE 8"),
        iv("B2 · Under 4", 2, "RPE 7", "82–94 rpm"), iv("B2 · Over 4", 1, "RPE 8"),
        iv("Recovery", 7, "RPE 2–3"),
        iv("B3 · Under 1", 2, "RPE 7", "82–94 rpm"), iv("B3 · Over 1", 1, "RPE 8"),
        iv("B3 · Under 2", 2, "RPE 7", "82–94 rpm"), iv("B3 · Over 2", 1, "RPE 8"),
        iv("B3 · Under 3", 2, "RPE 7", "82–94 rpm"), iv("B3 · Over 3", 1, "RPE 8"),
        iv("B3 · Under 4", 2, "RPE 7", "82–94 rpm"), iv("B3 · Over 4", 1, "RPE 8"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two blocks, or reduce each block to three over-under repeats.",
      notes: "Begin each block conservatively, return immediately to RPE 7 after each surge without coasting, and keep the final block consistent.",
      completionMessage: "Control the surge, settle back into strength and keep moving forward.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Aerobic Endurance and Leg Speed", rideLabel: "Ride 26",
      duration: "75–90 min", category: "Aerobic Maintenance and High-Cadence Efficiency", environment: "Indoor or outdoor",
      goal: "Fast legs should feel light and precise — not rushed.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Spin-Up 1", 0.33, "RPE 4", "100–110 rpm"), iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 2", 0.33, "RPE 4", "100–110 rpm"), iv("Recovery", 1, "RPE 2–3"),
        iv("Spin-Up 3", 0.33, "RPE 4", "100–110 rpm"), iv("Recovery", 1, "RPE 2–3"),
        iv("Build", 2, "RPE 4"),
        iv("Leg-Speed 1", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 2", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 3", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 4", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 5", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 6", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 7", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 1.66, "RPE 2–3"),
        iv("Leg-Speed 8", 0.33, "RPE 5", "110–120 rpm"), iv("Recovery", 2, "RPE 2–3"),
        iv("Aerobic 1", 5, "RPE 5", "95–100 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Aerobic 2", 5, "RPE 5", "95–100 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Aerobic 3", 5, "RPE 5", "95–100 rpm"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete six leg-speed efforts and two aerobic blocks; keep everything light and controlled.",
      notes: "Use light-to-moderate resistance for the leg-speed efforts — controlled cadence, not maximal sprints. Keep hips stable and avoid bouncing.",
      completionMessage: "Fast legs should feel light and precise — not rushed.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Goal Simulation Ride", rideLabel: "Ride 27",
      duration: "180–240 min", category: "Goal-Specific Pacing, Performance and Preparation", environment: "Indoor or outdoor",
      goal: "Simulation turns preparation into confidence.",
      intervals: [
        iv("Controlled Opening", 50, "RPE 3–4"),
        iv("Tempo 1", 20, "RPE 6", "82–95 rpm"), iv("Recovery", 10, "RPE 3"),
        iv("Tempo 2", 20, "RPE 6", "82–95 rpm"), iv("Recovery", 10, "RPE 3"),
        iv("Threshold 1", 10, "RPE 7", "82–94 rpm"), iv("Recovery", 7, "RPE 3"),
        iv("Threshold 2", 10, "RPE 7", "82–94 rpm"), iv("Recovery", 7, "RPE 3"),
        iv("Surge 1", 2, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Surge 2", 2, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Surge 3", 2, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Surge 4", 2, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Endurance Finish", 20, "RPE 3–5"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Reduce to one tempo block and one threshold effort; omit the surges if readiness is low.",
      notes: "Rehearse the Achievement Ride: test clothing, tyres, nutrition storage and pacing screens. Climbers ride efforts on climbs; endurance riders use steady terrain; event riders use rolling terrain. Fuel before the second-half efforts.",
      completionMessage: "Simulation turns preparation into confidence.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 10
const week10: Week = {
  number: 10,
  title: "Peak Performance Load",
  objective: "The highest goal-specific training load of the program: a sustained performance workout, a controlled sharpener and the longest or most demanding ride.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Sustained Goal Effort", rideLabel: "Ride 28",
      duration: "95–110 min", category: "Goal-Specific Sustainable Performance", environment: "Indoor or outdoor",
      goal: "Train the performance your goal will ask you to deliver.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Opener 1", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 1", 0.5, "RPE 7–8"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 2", 0.5, "RPE 7–8"),
        iv("Settle", 2, "RPE 2–3"),
        iv("Goal Effort 1", 25, "RPE 6", "82–95 rpm"),
        iv("Recovery", 8, "RPE 2–3"),
        iv("Goal Effort 2", 25, "RPE 6", "82–95 rpm"),
        iv("Cool-Down", 13, "RPE 1–2"),
      ],
      easierOption: "Reduce each sustained effort to 20 minutes.",
      notes: "Choose the main set for your goal — Long-distance: 2×25 min @RPE6 (shown here). Climbing: 4×10 min @RPE7 (65–85 rpm, mostly seated). Event/speed: 3×12 min @RPE7 with a 30s RPE8 surge every 3 minutes.",
      completionMessage: "Train the performance your goal will ask you to deliver.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~30 min" },
    {
      day: "Thursday", type: "cycling", title: "Endurance with Leg Openers", rideLabel: "Ride 29",
      duration: "70–85 min", category: "Aerobic Maintenance and Performance Activation", environment: "Indoor or outdoor",
      goal: "Open the legs, wake up the power and save the best work for the weekend.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Build", 3, "RPE 4"),
        iv("Spin-Up 1", 0.33, "RPE 4", "100–110 rpm"), iv("Recovery", 0.66, "RPE 2–3"),
        iv("Spin-Up 2", 0.33, "RPE 4", "100–110 rpm"),
        iv("Endurance", 6, "RPE 3–4"),
        iv("Opener 1", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 4", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 5", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 6", 1, "RPE 8", "90–105 rpm"), iv("Recovery", 3, "RPE 2–3"),
        iv("Endurance Finish", 8, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Complete four openers; end the set if quality declines substantially.",
      completionMessage: "Open the legs, wake up the power and save the best work for the weekend.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Peak Goal-Specific Training Ride", rideLabel: "Ride 30",
      duration: "210–270 min", category: "Peak Endurance and Goal-Specific Performance", environment: "Indoor or outdoor",
      goal: "Your peak ride should prove your preparation — not empty everything you have.",
      intervals: [
        iv("Controlled Endurance 1", 45, "RPE 3–4"),
        iv("Controlled Endurance 2", 30, "RPE 3–4"),
        iv("Tempo 1", 25, "RPE 6", "82–95 rpm"), iv("Recovery", 10, "RPE 3"),
        iv("Tempo 2", 25, "RPE 6", "82–95 rpm"), iv("Recovery", 10, "RPE 3"),
        iv("Threshold 1", 12, "RPE 7", "82–94 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Threshold 2", 12, "RPE 7", "82–94 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Surge 1", 2, "RPE 8"), iv("Recovery", 4, "RPE 3"),
        iv("Surge 2", 2, "RPE 8"), iv("Recovery", 4, "RPE 3"),
        iv("Surge 3", 2, "RPE 8"), iv("Recovery", 4, "RPE 3"),
        iv("Endurance Finish", 20, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Omit the optional surges and reduce tempo to 2×20 minutes if threshold quality, fuelling or coordination declines.",
      notes: "The longest ride of the plan. Long-distance: prioritise sustained tempo. Climbing: complete efforts on climbs. Event/speed: use rolling terrain. Fuel from the first hour; shorten or modify for unsafe conditions, declining coordination, or new pain.",
      completionMessage: "Your peak ride should prove your preparation — not empty everything you have.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 11
const week11: Week = {
  number: 11,
  title: "Sharpen and Build Confidence",
  weekType: "Volume reduction with maintained sharpness",
  objective: "Reduce volume while maintaining threshold and high-intensity sharpness; complete a final confidence simulation without excessive fatigue.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Controlled Sharpening", rideLabel: "Ride 31",
      duration: "75–90 min", category: "Threshold Maintenance and High-Intensity Sharpness", environment: "Indoor or outdoor",
      goal: "Sharpness comes from quality — not from squeezing in more fatigue.",
      intervals: [
        iv("Warm-Up", 8, "RPE 2–3"),
        iv("Build", 5, "RPE 4"),
        iv("Opener 1", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 6"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 1", 0.33, "RPE 7–8"), iv("Recovery", 1, "RPE 2–3"),
        iv("Primer 2", 0.33, "RPE 7–8"),
        iv("Settle", 2, "RPE 2–3"),
        iv("Threshold 1", 6, "RPE 7–8", "82–94 rpm"), iv("Recovery", 5, "RPE 2–3"),
        iv("Threshold 2", 6, "RPE 7–8", "82–94 rpm"), iv("Recovery", 5, "RPE 2–3"),
        iv("Threshold 3", 6, "RPE 7–8", "82–94 rpm"), iv("Recovery", 5, "RPE 2–3"),
        iv("Sharp 1", 1, "RPE 8–9"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 2", 1, "RPE 8–9"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 3", 1, "RPE 8–9"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 4", 1, "RPE 8–9"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete two threshold intervals and three short efforts; stop before technique deteriorates.",
      completionMessage: "Sharpness comes from quality — not from squeezing in more fatigue.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Cycling Strength", duration: "~25 min" },
    {
      day: "Thursday", type: "cycling", title: "Steady Endurance and Technique", rideLabel: "Ride 32",
      duration: "60–75 min", category: "Aerobic Maintenance and Technical Confidence", environment: "Indoor or outdoor",
      goal: "Confidence grows when the simple things become smooth and automatic.",
      intervals: [
        iv("Easy Start", 8, "RPE 2–3"),
        iv("Cadence 1", 3, "RPE 4", "95–105 rpm"), iv("Recovery", 3, "RPE 2"),
        iv("Cadence 2", 3, "RPE 4", "95–105 rpm"), iv("Recovery", 3, "RPE 2"),
        iv("Cadence 3", 3, "RPE 4", "95–105 rpm"), iv("Recovery", 3, "RPE 2"),
        iv("Cadence 4", 3, "RPE 4", "95–105 rpm"), iv("Recovery", 3, "RPE 2"),
        iv("Steady Aerobic", 14, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Keep the whole ride at RPE 2–3 if recovery is the priority.",
      notes: "Practise gear selection, cornering, braking, drinking while riding and looking ahead — all within safe conditions and your experience.",
      completionMessage: "Confidence grows when the simple things become smooth and automatic.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Achievement Confidence Simulation", rideLabel: "Ride 33",
      duration: "150–195 min", category: "Final Endurance Rehearsal and Confidence", environment: "Indoor or outdoor",
      goal: "You do not need to prove your fitness today. You only need to trust it.",
      intervals: [
        iv("Controlled Opening", 45, "RPE 3–4"),
        iv("Steady Endurance", 20, "RPE 3–4"),
        iv("Goal Pace 1", 15, "RPE 6", "82–95 rpm"), iv("Recovery", 9, "RPE 3"),
        iv("Goal Pace 2", 15, "RPE 6", "82–95 rpm"), iv("Recovery", 9, "RPE 3"),
        iv("Threshold", 8, "RPE 7", "82–94 rpm"), iv("Recovery", 6, "RPE 3"),
        iv("Sharp 1", 1, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 2", 1, "RPE 8"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 3", 1, "RPE 8"),
        iv("Endurance Finish", 22, "RPE 3–4"),
        iv("Cool-Down", 10, "RPE 1–2"),
      ],
      easierOption: "Reduce goal-pace blocks to 10 minutes and skip the short efforts; keep the finish smooth.",
      notes: "The final substantial rehearsal — confidence, not another peak load. Confirm bicycle setup, clothing, nutrition, hydration, route and pacing. Resist the urge to overperform.",
      completionMessage: "You do not need to prove your fitness today. You only need to trust it.",
    },
    { day: "Sunday", type: "recovery", title: "Optional Recovery Spin or Rest", duration: "optional", optional: true },
  ],
};

// ---------------------------------------------------------------- WEEK 12
const week12: Week = {
  number: 12,
  title: "Taper and Achievement",
  weekType: "Taper — reduced volume, maintained sharpness",
  objective: "Reduce training load while preserving sharpness, then complete the personalised Ride Beyond Achievement Ride rested and confident.",
  days: [
    restDay(),
    {
      day: "Tuesday", type: "cycling", title: "Achievement Confidence Ride", rideLabel: "Ride 34",
      duration: "60–75 min", category: "Maintaining Confidence and Goal-Pace Rhythm", environment: "Indoor or outdoor",
      goal: "Confidence is knowing you could do more — and choosing to save it.",
      intervals: [
        iv("Warm-Up", 10, "RPE 2–3"),
        iv("Build", 3, "RPE 4"),
        iv("Spin-Up 1", 0.33, "RPE 4", "100–110 rpm"), iv("Recovery", 0.66, "RPE 2–3"),
        iv("Spin-Up 2", 0.33, "RPE 4", "100–110 rpm"),
        iv("Goal Pace 1", 8, "RPE 6", "82–95 rpm"), iv("Recovery", 5, "RPE 2–3"),
        iv("Goal Pace 2", 8, "RPE 6", "82–95 rpm"), iv("Recovery", 5, "RPE 2–3"),
        iv("Tempo Surge 1", 2, "RPE 7"), iv("Recovery", 3, "RPE 2–3"),
        iv("Tempo Surge 2", 2, "RPE 7"), iv("Recovery", 3, "RPE 2–3"),
        iv("Tempo Surge 3", 2, "RPE 7"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Complete one goal-pace block and two tempo surges; do not exceed the planned intensity.",
      completionMessage: "Confidence is knowing you could do more — and choosing to save it.",
    },
    { day: "Wednesday", type: "strength", title: "Fit Beyond 50 — Gentle Mobility", duration: "~20 min" },
    {
      day: "Thursday", type: "cycling", title: "Leg Opener and Goal Skills Ride", rideLabel: "Ride 35",
      duration: "40–55 min", category: "Activation and Final Preparation", environment: "Indoor or outdoor",
      goal: "Wake up the legs, settle the mind and leave the rest for Achievement Day.",
      intervals: [
        iv("Easy Opening", 15, "RPE 2–3"),
        iv("Opener 1", 1, "RPE 7"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 2", 1, "RPE 7"), iv("Recovery", 3, "RPE 2–3"),
        iv("Opener 3", 1, "RPE 7"), iv("Recovery", 3, "RPE 2–3"),
        iv("Sharp 1", 0.33, "RPE 8"), iv("Recovery", 2, "RPE 2–3"),
        iv("Sharp 2", 0.33, "RPE 8"), iv("Recovery", 2, "RPE 2–3"),
        iv("Sharp 3", 0.33, "RPE 8"), iv("Recovery", 2, "RPE 2–3"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Reduce to two openers and two short efforts — these are controlled openers, not maximal.",
      notes: "Confirm gears, brakes, tyres, sensors, nutrition, clothing and spares are ready for Achievement Day.",
      completionMessage: "Wake up the legs, settle the mind and leave the rest for Achievement Day.",
    },
    recoveryDay("Rest or Gentle Mobility", "optional"),
    {
      day: "Saturday", type: "cycling", title: "Ride Beyond Achievement Ride", rideLabel: "Ride 36",
      duration: "Personalised · goal-specific", category: "Personalised Advanced Cycling Achievement", environment: "Indoor or outdoor",
      goal: "Complete a meaningful advanced challenge with control, confidence and intelligent pacing.",
      intervals: [
        iv("Opening Quarter", 40, "RPE 3–4"),
        iv("Goal Intensity 1", 20, "RPE 6", "82–95 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Goal Intensity 2", 20, "RPE 6", "82–95 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Goal Threshold 1", 12, "RPE 7", "82–94 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Goal Threshold 2", 12, "RPE 7", "82–94 rpm"), iv("Recovery", 8, "RPE 3"),
        iv("Steady Endurance", 20, "RPE 3–4"),
        iv("Final Quarter", 15, "RPE 4–6"),
        iv("Cool-Down", 12, "RPE 1–2"),
      ],
      easierOption: "Foundation Achievement — a 2–3 hour ride primarily at RPE 3–4 with two optional tempo blocks, ridden only when you feel good. This remains a successful completion of Ride Beyond.",
      notes: "Choose your level: FULL (4–5 h endurance / 100–130 km / major climb / event, with 60–90 min goal intensity), SUPPORTED (3–4 h / 80–110 km with 40–60 min tempo-threshold), or FOUNDATION (2–3 h controlled endurance). Begin below what feels possible, fuel early, hold goal pace rather than early speed, and finish strong only when readiness is good. Reduce effort, shorten or stop for chest discomfort, dizziness, new/worsening pain, loss of coordination, or unsafe conditions.",
      completionMessage:
        "You did not simply finish the plan — you learned how to Ride Beyond. Your strongest performance came from consistency, intelligent recovery and disciplined pacing. Ride Beyond — stronger for longer, ready when the road demands more.",
    },
    { day: "Sunday", type: "recovery", title: "Post-Achievement Recovery — Rest or Gentle Spin", duration: "optional", optional: true },
  ],
  reflection: [
    "Did you pace the opening quarter conservatively and fuel from early on?",
    "Did your goal-specific efforts stay controlled and consistent?",
    "Did you select the Achievement level that matched your readiness?",
    "Did you finish tired but coordinated and in control?",
    "Have you planned several days of reduced training to recover well?",
  ],
};

const phase3: Phase = {
  number: 3,
  name: "Performance Ready",
  weeksLabel: "Weeks 9–12",
  objective:
    "Convert eight weeks of fitness into goal-specific performance — changes of pace, over-unders, goal-pace efforts and disciplined long-ride pacing — then taper to arrive at the Achievement Ride rested and confident.",
  focus: [
    "Over-under intervals and smooth changes of pace.",
    "Sustained goal-specific tempo and threshold power.",
    "Quality effort after accumulated fatigue.",
    "Goal-specific fuelling, hydration and equipment rehearsal.",
    "Strategic taper — maintain fitness while volume reduces.",
    "Readiness judgement and the personalised Achievement Ride.",
  ],
  milestone: [
    "Complete controlled over-under intervals and respond smoothly to changes of pace.",
    "Sustain goal-specific tempo and threshold work under fatigue.",
    "Maintain pacing on demanding terrain with an effective fuelling strategy.",
    "Reduce training load without adding unnecessary sessions.",
    "Recognise personal readiness and select the appropriate Achievement level.",
    "Complete a meaningful advanced cycling challenge safely and confidently.",
  ],
  cadenceQuote: "Control the surge, settle back into strength and keep moving forward.",
  weeks: [week9, week10, week11, week12],
  complete: {
    heading: "PHASE 3 COMPLETE — YOU LEARNED HOW TO RIDE BEYOND",
    summary: [
      "Twelve weeks completed; thirty-six advanced cycling workouts available.",
      "Baseline established, sustainable power developed, climbing strength built.",
      "Over-unders, goal-pace efforts and quality work under fatigue mastered.",
      "Goal-specific fuelling, pacing and equipment rehearsed and confirmed.",
      "A strategic taper completed — arriving rested rather than overtrained.",
      "A personalised Ride Beyond Achievement Ride completed with control.",
    ],
    coachMessage:
      "You have completed more than twelve weeks of training. You established your baseline, developed sustainable power, built climbing strength and learned to produce quality effort after fatigue began to build. Your strongest performance was not one heroic workout — it was consistency, intelligent recovery, disciplined pacing and the confidence to ride according to your own readiness. You did not simply finish the plan. You learned how to Ride Beyond — stronger for longer, ready when the road demands more.",
  },
};

export const RIDE_BEYOND: Program = {
  id: "ride-beyond",
  name: "Ride Beyond",
  level: "Advanced",
  durationWeeks: 12,
  phaseCount: 3,
  frequency: "3 rides/week",
  outcome:
    "An advanced 12-week performance plan — sustainable power, endurance, climbing strength, cadence control and performance under fatigue, toward a personalised achievement ride.",
  startDate: "2025-05-12",
  weeklyRhythm: [
    { day: "Mon", session: "Rest" },
    { day: "Tue", session: "Primary Workout" },
    { day: "Wed", session: "FB50 Strength" },
    { day: "Thu", session: "Secondary Workout" },
    { day: "Fri", session: "Rest / Recovery" },
    { day: "Sat", session: "Long Ride" },
    { day: "Sun", session: "Optional Recovery" },
  ],
  phaseTitles: [
    { number: 1, name: "Performance Foundation", weeks: "Weeks 1–4" },
    { number: 2, name: "Power and Durability", weeks: "Weeks 5–8" },
    { number: 3, name: "Performance Ready", weeks: "Weeks 9–12" },
  ],
  phases: [phase1, phase2, phase3],
  endMessage:
    "YOU RODE BEYOND. Twelve weeks ago you began with the fitness, experience and ambition to become a stronger rider. Since then you have established your performance baseline, strengthened your aerobic foundation and gained control over cadence, pacing and effort. You have built sustainable power, improved your climbing strength and learned to repeat demanding efforts, ride with purpose under fatigue and make better decisions when the road turns hard. Advanced performance is not one number, one workout or one heroic ride — it is consistency, intelligent progression, disciplined recovery and the confidence to ride according to your own readiness. Your Achievement Ride completes this program, but not your progress. Take time to recover and reflect on how far you have come. Your next ride begins with a stronger foundation and a new level of confidence in the rider you have become. Ride Beyond — stronger for longer, ready when the road demands more. Your strongest ride is your own.",
};

export function rbRideId(s: Session): string {
  const m = s.rideLabel?.match(/Ride\s+(\d+)/i);
  if (m) return `rb-ride-${m[1]}`;
  return `rb-${s.day.toLowerCase()}-${s.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}`;
}

export function rbWeekStart(weekNumber: number): string {
  const [y, m, d] = RIDE_BEYOND.startDate.split("-").map((n) => parseInt(n, 10));
  const base = new Date(Date.UTC(y, m - 1, d));
  base.setUTCDate(base.getUTCDate() + (weekNumber - 1) * 7);
  return base.toISOString().slice(0, 10);
}
